# Generated by Django 3.2 on 2021-04-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='mv',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
