# Generated by Django 3.2 on 2021-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_asset_mv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSE', 'close'), ('ERROR', 'error')], max_length=10),
        ),
    ]
