# Generated by Django 3.2 on 2021-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSE', 'close'), ('ERROR', 'error')], default='OPEN', max_length=10),
        ),
    ]
