# Generated by Django 3.2 on 2021-04-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='product',
            field=models.CharField(default='BTCUSDT', max_length=20),
        ),
    ]
