# Generated by Django 3.2 on 2021-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_asset_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='work',
            field=models.BooleanField(default=0),
        ),
    ]
