# Generated by Django 3.2 on 2021-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210428_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='product',
            field=models.CharField(choices=[('BNB', 'BNB'), ('BTC', 'BTC'), ('BUSD', 'BUSD'), ('ETH', 'ETH'), ('LTC', 'LTC'), ('TRX', 'TRX'), ('USDT', 'USDT'), ('XRP', 'XRP')], max_length=20),
        ),
    ]
