# Generated by Django 3.2 on 2021-04-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_asset_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='volume',
            new_name='quantity',
        ),
    ]
