# Generated by Django 3.2 on 2021-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_rename_volume_asset_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='product',
            field=models.CharField(default='BTCUSDT', max_length=20),
        ),
    ]
