# Generated by Django 3.2 on 2021-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_asset_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('ERROR', 'ERROR')], default='OPEN', max_length=10),
        ),
    ]
