# Generated by Django 3.2 on 2021-04-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_asset_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='mv',
            new_name='ma',
        ),
    ]
